webform.settings.third_party.hcl_domain_webform:
  type: mapping
  label: 'Webform hcl_domain_webform configuration'
  mapping:
    settings:
      type: mapping
      label: 'hcl_domain_webform settings'
      mapping:
        domain_id:
          type: string
          label: 'Domain Access'

# Schema for the configuration files of the hcl_domain_webform module.
# hcl_domain_webform.settings:
#   type: config_object
#   label: 'hcl_domain_webform settings'
#   mapping:
#     roles_to_restrict:
#       type: string
#       label: 'Roles to restrict'
